/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ArcadeRouteImport } from './routes/arcade'
import { Route as CameraRouteImport } from './routes/camera'
import { Route as MatchRouteImport } from './routes/match'
import { Route as MuralRouteImport } from './routes/mural'
import { Route as PanicoRouteImport } from './routes/panico'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ArcadeRoute = ArcadeRouteImport.update({
  id: '/arcade',
  path: '/arcade',
  getParentRoute: () => rootRouteImport,
} as any)
const CameraRoute = CameraRouteImport.update({
  id: '/camera',
  path: '/camera',
  getParentRoute: () => rootRouteImport,
} as any)
const MatchRoute = MatchRouteImport.update({
  id: '/match',
  path: '/match',
  getParentRoute: () => rootRouteImport,
} as any)
const MuralRoute = MuralRouteImport.update({
  id: '/mural',
  path: '/mural',
  getParentRoute: () => rootRouteImport,
} as any)
const PanicoRoute = PanicoRouteImport.update({
  id: '/panico',
  path: '/panico',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/arcade': typeof ArcadeRoute
  '/camera': typeof CameraRoute
  '/match': typeof MatchRoute
  '/mural': typeof MuralRoute
  '/panico': typeof PanicoRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/arcade': typeof ArcadeRoute
  '/camera': typeof CameraRoute
  '/match': typeof MatchRoute
  '/mural': typeof MuralRoute
  '/panico': typeof PanicoRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/arcade': typeof ArcadeRoute
  '/camera': typeof CameraRoute
  '/match': typeof MatchRoute
  '/mural': typeof MuralRoute
  '/panico': typeof PanicoRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/arcade' | '/camera' | '/match' | '/mural' | '/panico'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/arcade' | '/camera' | '/match' | '/mural' | '/panico'
  id: '__root__' | '/' | '/arcade' | '/camera' | '/match' | '/mural' | '/panico'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ArcadeRoute: typeof ArcadeRoute
  CameraRoute: typeof CameraRoute
  MatchRoute: typeof MatchRoute
  MuralRoute: typeof MuralRoute
  PanicoRoute: typeof PanicoRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/arcade': {
      id: '/arcade'
      path: '/arcade'
      fullPath: '/arcade'
      preLoaderRoute: typeof ArcadeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/camera': {
      id: '/camera'
      path: '/camera'
      fullPath: '/camera'
      preLoaderRoute: typeof CameraRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/match': {
      id: '/match'
      path: '/match'
      fullPath: '/match'
      preLoaderRoute: typeof MatchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mural': {
      id: '/mural'
      path: '/mural'
      fullPath: '/mural'
      preLoaderRoute: typeof MuralRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/panico': {
      id: '/panico'
      path: '/panico'
      fullPath: '/panico'
      preLoaderRoute: typeof PanicoRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ArcadeRoute: ArcadeRoute,
  CameraRoute: CameraRoute,
  MatchRoute: MatchRoute,
  MuralRoute: MuralRoute,
  PanicoRoute: PanicoRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
