/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ArcadeRouteImport } from './routes/arcade'
import { Route as CameraRouteImport } from './routes/camera'
import { Route as LojaRouteImport } from './routes/loja'
import { Route as MatchRouteImport } from './routes/match'
import { Route as MuralRouteImport } from './routes/mural'
import { Route as PanicoRouteImport } from './routes/panico'
import { Route as QrcodesRouteImport } from './routes/qrcodes'
import { Route as RankingRouteImport } from './routes/ranking'
import { Route as QCodigoRouteImport } from './routes/q.$codigo'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ArcadeRoute = ArcadeRouteImport.update({
  id: '/arcade',
  path: '/arcade',
  getParentRoute: () => rootRouteImport,
} as any)
const CameraRoute = CameraRouteImport.update({
  id: '/camera',
  path: '/camera',
  getParentRoute: () => rootRouteImport,
} as any)
const LojaRoute = LojaRouteImport.update({
  id: '/loja',
  path: '/loja',
  getParentRoute: () => rootRouteImport,
} as any)
const MatchRoute = MatchRouteImport.update({
  id: '/match',
  path: '/match',
  getParentRoute: () => rootRouteImport,
} as any)
const MuralRoute = MuralRouteImport.update({
  id: '/mural',
  path: '/mural',
  getParentRoute: () => rootRouteImport,
} as any)
const PanicoRoute = PanicoRouteImport.update({
  id: '/panico',
  path: '/panico',
  getParentRoute: () => rootRouteImport,
} as any)
const QrcodesRoute = QrcodesRouteImport.update({
  id: '/qrcodes',
  path: '/qrcodes',
  getParentRoute: () => rootRouteImport,
} as any)
const RankingRoute = RankingRouteImport.update({
  id: '/ranking',
  path: '/ranking',
  getParentRoute: () => rootRouteImport,
} as any)
const QCodigoRoute = QCodigoRouteImport.update({
  id: '/q/$codigo',
  path: '/q/$codigo',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/arcade': typeof ArcadeRoute
  '/camera': typeof CameraRoute
  '/loja': typeof LojaRoute
  '/match': typeof MatchRoute
  '/mural': typeof MuralRoute
  '/panico': typeof PanicoRoute
  '/qrcodes': typeof QrcodesRoute
  '/ranking': typeof RankingRoute
  '/q/$codigo': typeof QCodigoRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/arcade': typeof ArcadeRoute
  '/camera': typeof CameraRoute
  '/loja': typeof LojaRoute
  '/match': typeof MatchRoute
  '/mural': typeof MuralRoute
  '/panico': typeof PanicoRoute
  '/qrcodes': typeof QrcodesRoute
  '/ranking': typeof RankingRoute
  '/q/$codigo': typeof QCodigoRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/arcade': typeof ArcadeRoute
  '/camera': typeof CameraRoute
  '/loja': typeof LojaRoute
  '/match': typeof MatchRoute
  '/mural': typeof MuralRoute
  '/panico': typeof PanicoRoute
  '/qrcodes': typeof QrcodesRoute
  '/ranking': typeof RankingRoute
  '/q/$codigo': typeof QCodigoRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/arcade'
    | '/camera'
    | '/loja'
    | '/match'
    | '/mural'
    | '/panico'
    | '/qrcodes'
    | '/ranking'
    | '/q/$codigo'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/arcade'
    | '/camera'
    | '/loja'
    | '/match'
    | '/mural'
    | '/panico'
    | '/qrcodes'
    | '/ranking'
    | '/q/$codigo'
  id:
    | '__root__'
    | '/'
    | '/arcade'
    | '/camera'
    | '/loja'
    | '/match'
    | '/mural'
    | '/panico'
    | '/qrcodes'
    | '/ranking'
    | '/q/$codigo'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ArcadeRoute: typeof ArcadeRoute
  CameraRoute: typeof CameraRoute
  LojaRoute: typeof LojaRoute
  MatchRoute: typeof MatchRoute
  MuralRoute: typeof MuralRoute
  PanicoRoute: typeof PanicoRoute
  QrcodesRoute: typeof QrcodesRoute
  RankingRoute: typeof RankingRoute
  QCodigoRoute: typeof QCodigoRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/arcade': {
      id: '/arcade'
      path: '/arcade'
      fullPath: '/arcade'
      preLoaderRoute: typeof ArcadeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/camera': {
      id: '/camera'
      path: '/camera'
      fullPath: '/camera'
      preLoaderRoute: typeof CameraRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/loja': {
      id: '/loja'
      path: '/loja'
      fullPath: '/loja'
      preLoaderRoute: typeof LojaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/match': {
      id: '/match'
      path: '/match'
      fullPath: '/match'
      preLoaderRoute: typeof MatchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mural': {
      id: '/mural'
      path: '/mural'
      fullPath: '/mural'
      preLoaderRoute: typeof MuralRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/panico': {
      id: '/panico'
      path: '/panico'
      fullPath: '/panico'
      preLoaderRoute: typeof PanicoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/qrcodes': {
      id: '/qrcodes'
      path: '/qrcodes'
      fullPath: '/qrcodes'
      preLoaderRoute: typeof QrcodesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ranking': {
      id: '/ranking'
      path: '/ranking'
      fullPath: '/ranking'
      preLoaderRoute: typeof RankingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/q/$codigo': {
      id: '/q/$codigo'
      path: '/q/$codigo'
      fullPath: '/q/$codigo'
      preLoaderRoute: typeof QCodigoRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ArcadeRoute: ArcadeRoute,
  CameraRoute: CameraRoute,
  LojaRoute: LojaRoute,
  MatchRoute: MatchRoute,
  MuralRoute: MuralRoute,
  PanicoRoute: PanicoRoute,
  QrcodesRoute: QrcodesRoute,
  RankingRoute: RankingRoute,
  QCodigoRoute: QCodigoRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
