/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppRouteImport } from './routes/app'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AppIndexRouteImport } from './routes/app.index'
import { Route as AppBackupsRouteImport } from './routes/app.backups'
import { Route as AppBiRouteImport } from './routes/app.bi'
import { Route as AppCargasRouteImport } from './routes/app.cargas'
import { Route as AppCentralRouteImport } from './routes/app.central'
import { Route as AppConsumoRouteImport } from './routes/app.consumo'
import { Route as AppConsumoTempoRouteImport } from './routes/app.consumo-tempo'
import { Route as AppEstoqueRouteImport } from './routes/app.estoque'
import { Route as AppGovernancaRouteImport } from './routes/app.governanca'
import { Route as AppImportarRouteImport } from './routes/app.importar'
import { Route as AppInventariosRouteImport } from './routes/app.inventarios'
import { Route as AppMapRouteImport } from './routes/app.map'
import { Route as AppNotasRouteImport } from './routes/app.notas'
import { Route as AppPerfilRouteImport } from './routes/app.perfil'
import { Route as AppRelatorioRouteImport } from './routes/app.relatorio'
import { Route as RBarIdRouteImport } from './routes/r.$barId'
import { Route as AppBarsBarIdRouteImport } from './routes/app.bars.$barId'
import { Route as AppBarsNewRouteImport } from './routes/app.bars.new'
import { Route as AppEquipeBarIndexRouteImport } from './routes/app.equipe-bar.index'
import { Route as AppEquipeBarBarIdRouteImport } from './routes/app.equipe-bar.$barId'
import { Route as AppManutencaoIndexRouteImport } from './routes/app.manutencao.index'
import { Route as AppManutencaoBarIdRouteImport } from './routes/app.manutencao.$barId'
import { Route as RTCodeRouteImport } from './routes/r.t.$code'
import { Route as ApiPublicBackupDailyRouteImport } from './routes/api/public/backup.daily'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppBackupsRoute = AppBackupsRouteImport.update({
  id: '/backups',
  path: '/backups',
  getParentRoute: () => AppRoute,
} as any)
const AppBiRoute = AppBiRouteImport.update({
  id: '/bi',
  path: '/bi',
  getParentRoute: () => AppRoute,
} as any)
const AppCargasRoute = AppCargasRouteImport.update({
  id: '/cargas',
  path: '/cargas',
  getParentRoute: () => AppRoute,
} as any)
const AppCentralRoute = AppCentralRouteImport.update({
  id: '/central',
  path: '/central',
  getParentRoute: () => AppRoute,
} as any)
const AppConsumoRoute = AppConsumoRouteImport.update({
  id: '/consumo',
  path: '/consumo',
  getParentRoute: () => AppRoute,
} as any)
const AppConsumoTempoRoute = AppConsumoTempoRouteImport.update({
  id: '/consumo-tempo',
  path: '/consumo-tempo',
  getParentRoute: () => AppRoute,
} as any)
const AppEstoqueRoute = AppEstoqueRouteImport.update({
  id: '/estoque',
  path: '/estoque',
  getParentRoute: () => AppRoute,
} as any)
const AppGovernancaRoute = AppGovernancaRouteImport.update({
  id: '/governanca',
  path: '/governanca',
  getParentRoute: () => AppRoute,
} as any)
const AppImportarRoute = AppImportarRouteImport.update({
  id: '/importar',
  path: '/importar',
  getParentRoute: () => AppRoute,
} as any)
const AppInventariosRoute = AppInventariosRouteImport.update({
  id: '/inventarios',
  path: '/inventarios',
  getParentRoute: () => AppRoute,
} as any)
const AppMapRoute = AppMapRouteImport.update({
  id: '/map',
  path: '/map',
  getParentRoute: () => AppRoute,
} as any)
const AppNotasRoute = AppNotasRouteImport.update({
  id: '/notas',
  path: '/notas',
  getParentRoute: () => AppRoute,
} as any)
const AppPerfilRoute = AppPerfilRouteImport.update({
  id: '/perfil',
  path: '/perfil',
  getParentRoute: () => AppRoute,
} as any)
const AppRelatorioRoute = AppRelatorioRouteImport.update({
  id: '/relatorio',
  path: '/relatorio',
  getParentRoute: () => AppRoute,
} as any)
const RBarIdRoute = RBarIdRouteImport.update({
  id: '/r/$barId',
  path: '/r/$barId',
  getParentRoute: () => rootRouteImport,
} as any)
const AppBarsBarIdRoute = AppBarsBarIdRouteImport.update({
  id: '/bars/$barId',
  path: '/bars/$barId',
  getParentRoute: () => AppRoute,
} as any)
const AppBarsNewRoute = AppBarsNewRouteImport.update({
  id: '/bars/new',
  path: '/bars/new',
  getParentRoute: () => AppRoute,
} as any)
const AppEquipeBarIndexRoute = AppEquipeBarIndexRouteImport.update({
  id: '/equipe-bar/',
  path: '/equipe-bar/',
  getParentRoute: () => AppRoute,
} as any)
const AppEquipeBarBarIdRoute = AppEquipeBarBarIdRouteImport.update({
  id: '/equipe-bar/$barId',
  path: '/equipe-bar/$barId',
  getParentRoute: () => AppRoute,
} as any)
const AppManutencaoIndexRoute = AppManutencaoIndexRouteImport.update({
  id: '/manutencao/',
  path: '/manutencao/',
  getParentRoute: () => AppRoute,
} as any)
const AppManutencaoBarIdRoute = AppManutencaoBarIdRouteImport.update({
  id: '/manutencao/$barId',
  path: '/manutencao/$barId',
  getParentRoute: () => AppRoute,
} as any)
const RTCodeRoute = RTCodeRouteImport.update({
  id: '/r/t/$code',
  path: '/r/t/$code',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicBackupDailyRoute = ApiPublicBackupDailyRouteImport.update({
  id: '/api/public/backup/daily',
  path: '/api/public/backup/daily',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/auth': typeof AuthRoute
  '/app/backups': typeof AppBackupsRoute
  '/app/bi': typeof AppBiRoute
  '/app/cargas': typeof AppCargasRoute
  '/app/central': typeof AppCentralRoute
  '/app/consumo': typeof AppConsumoRoute
  '/app/consumo-tempo': typeof AppConsumoTempoRoute
  '/app/estoque': typeof AppEstoqueRoute
  '/app/governanca': typeof AppGovernancaRoute
  '/app/importar': typeof AppImportarRoute
  '/app/inventarios': typeof AppInventariosRoute
  '/app/map': typeof AppMapRoute
  '/app/notas': typeof AppNotasRoute
  '/app/perfil': typeof AppPerfilRoute
  '/app/relatorio': typeof AppRelatorioRoute
  '/r/$barId': typeof RBarIdRoute
  '/app/': typeof AppIndexRoute
  '/app/bars/$barId': typeof AppBarsBarIdRoute
  '/app/bars/new': typeof AppBarsNewRoute
  '/app/equipe-bar/$barId': typeof AppEquipeBarBarIdRoute
  '/app/manutencao/$barId': typeof AppManutencaoBarIdRoute
  '/r/t/$code': typeof RTCodeRoute
  '/app/equipe-bar/': typeof AppEquipeBarIndexRoute
  '/app/manutencao/': typeof AppManutencaoIndexRoute
  '/api/public/backup/daily': typeof ApiPublicBackupDailyRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/app/backups': typeof AppBackupsRoute
  '/app/bi': typeof AppBiRoute
  '/app/cargas': typeof AppCargasRoute
  '/app/central': typeof AppCentralRoute
  '/app/consumo': typeof AppConsumoRoute
  '/app/consumo-tempo': typeof AppConsumoTempoRoute
  '/app/estoque': typeof AppEstoqueRoute
  '/app/governanca': typeof AppGovernancaRoute
  '/app/importar': typeof AppImportarRoute
  '/app/inventarios': typeof AppInventariosRoute
  '/app/map': typeof AppMapRoute
  '/app/notas': typeof AppNotasRoute
  '/app/perfil': typeof AppPerfilRoute
  '/app/relatorio': typeof AppRelatorioRoute
  '/r/$barId': typeof RBarIdRoute
  '/app': typeof AppIndexRoute
  '/app/bars/$barId': typeof AppBarsBarIdRoute
  '/app/bars/new': typeof AppBarsNewRoute
  '/app/equipe-bar/$barId': typeof AppEquipeBarBarIdRoute
  '/app/manutencao/$barId': typeof AppManutencaoBarIdRoute
  '/r/t/$code': typeof RTCodeRoute
  '/app/equipe-bar': typeof AppEquipeBarIndexRoute
  '/app/manutencao': typeof AppManutencaoIndexRoute
  '/api/public/backup/daily': typeof ApiPublicBackupDailyRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/auth': typeof AuthRoute
  '/app/backups': typeof AppBackupsRoute
  '/app/bi': typeof AppBiRoute
  '/app/cargas': typeof AppCargasRoute
  '/app/central': typeof AppCentralRoute
  '/app/consumo': typeof AppConsumoRoute
  '/app/consumo-tempo': typeof AppConsumoTempoRoute
  '/app/estoque': typeof AppEstoqueRoute
  '/app/governanca': typeof AppGovernancaRoute
  '/app/importar': typeof AppImportarRoute
  '/app/inventarios': typeof AppInventariosRoute
  '/app/map': typeof AppMapRoute
  '/app/notas': typeof AppNotasRoute
  '/app/perfil': typeof AppPerfilRoute
  '/app/relatorio': typeof AppRelatorioRoute
  '/r/$barId': typeof RBarIdRoute
  '/app/': typeof AppIndexRoute
  '/app/bars/$barId': typeof AppBarsBarIdRoute
  '/app/bars/new': typeof AppBarsNewRoute
  '/app/equipe-bar/$barId': typeof AppEquipeBarBarIdRoute
  '/app/manutencao/$barId': typeof AppManutencaoBarIdRoute
  '/r/t/$code': typeof RTCodeRoute
  '/app/equipe-bar/': typeof AppEquipeBarIndexRoute
  '/app/manutencao/': typeof AppManutencaoIndexRoute
  '/api/public/backup/daily': typeof ApiPublicBackupDailyRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/auth'
    | '/app/backups'
    | '/app/bi'
    | '/app/cargas'
    | '/app/central'
    | '/app/consumo'
    | '/app/consumo-tempo'
    | '/app/estoque'
    | '/app/governanca'
    | '/app/importar'
    | '/app/inventarios'
    | '/app/map'
    | '/app/notas'
    | '/app/perfil'
    | '/app/relatorio'
    | '/r/$barId'
    | '/app/'
    | '/app/bars/$barId'
    | '/app/bars/new'
    | '/app/equipe-bar/$barId'
    | '/app/manutencao/$barId'
    | '/r/t/$code'
    | '/app/equipe-bar/'
    | '/app/manutencao/'
    | '/api/public/backup/daily'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/app/backups'
    | '/app/bi'
    | '/app/cargas'
    | '/app/central'
    | '/app/consumo'
    | '/app/consumo-tempo'
    | '/app/estoque'
    | '/app/governanca'
    | '/app/importar'
    | '/app/inventarios'
    | '/app/map'
    | '/app/notas'
    | '/app/perfil'
    | '/app/relatorio'
    | '/r/$barId'
    | '/app'
    | '/app/bars/$barId'
    | '/app/bars/new'
    | '/app/equipe-bar/$barId'
    | '/app/manutencao/$barId'
    | '/r/t/$code'
    | '/app/equipe-bar'
    | '/app/manutencao'
    | '/api/public/backup/daily'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/auth'
    | '/app/backups'
    | '/app/bi'
    | '/app/cargas'
    | '/app/central'
    | '/app/consumo'
    | '/app/consumo-tempo'
    | '/app/estoque'
    | '/app/governanca'
    | '/app/importar'
    | '/app/inventarios'
    | '/app/map'
    | '/app/notas'
    | '/app/perfil'
    | '/app/relatorio'
    | '/r/$barId'
    | '/app/'
    | '/app/bars/$barId'
    | '/app/bars/new'
    | '/app/equipe-bar/$barId'
    | '/app/manutencao/$barId'
    | '/r/t/$code'
    | '/app/equipe-bar/'
    | '/app/manutencao/'
    | '/api/public/backup/daily'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  AuthRoute: typeof AuthRoute
  RBarIdRoute: typeof RBarIdRoute
  RTCodeRoute: typeof RTCodeRoute
  ApiPublicBackupDailyRoute: typeof ApiPublicBackupDailyRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/backups': {
      id: '/app/backups'
      path: '/backups'
      fullPath: '/app/backups'
      preLoaderRoute: typeof AppBackupsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/bi': {
      id: '/app/bi'
      path: '/bi'
      fullPath: '/app/bi'
      preLoaderRoute: typeof AppBiRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/cargas': {
      id: '/app/cargas'
      path: '/cargas'
      fullPath: '/app/cargas'
      preLoaderRoute: typeof AppCargasRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/central': {
      id: '/app/central'
      path: '/central'
      fullPath: '/app/central'
      preLoaderRoute: typeof AppCentralRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/consumo': {
      id: '/app/consumo'
      path: '/consumo'
      fullPath: '/app/consumo'
      preLoaderRoute: typeof AppConsumoRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/consumo-tempo': {
      id: '/app/consumo-tempo'
      path: '/consumo-tempo'
      fullPath: '/app/consumo-tempo'
      preLoaderRoute: typeof AppConsumoTempoRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/estoque': {
      id: '/app/estoque'
      path: '/estoque'
      fullPath: '/app/estoque'
      preLoaderRoute: typeof AppEstoqueRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/governanca': {
      id: '/app/governanca'
      path: '/governanca'
      fullPath: '/app/governanca'
      preLoaderRoute: typeof AppGovernancaRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/importar': {
      id: '/app/importar'
      path: '/importar'
      fullPath: '/app/importar'
      preLoaderRoute: typeof AppImportarRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/inventarios': {
      id: '/app/inventarios'
      path: '/inventarios'
      fullPath: '/app/inventarios'
      preLoaderRoute: typeof AppInventariosRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/map': {
      id: '/app/map'
      path: '/map'
      fullPath: '/app/map'
      preLoaderRoute: typeof AppMapRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/notas': {
      id: '/app/notas'
      path: '/notas'
      fullPath: '/app/notas'
      preLoaderRoute: typeof AppNotasRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/perfil': {
      id: '/app/perfil'
      path: '/perfil'
      fullPath: '/app/perfil'
      preLoaderRoute: typeof AppPerfilRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/relatorio': {
      id: '/app/relatorio'
      path: '/relatorio'
      fullPath: '/app/relatorio'
      preLoaderRoute: typeof AppRelatorioRouteImport
      parentRoute: typeof AppRoute
    }
    '/r/$barId': {
      id: '/r/$barId'
      path: '/r/$barId'
      fullPath: '/r/$barId'
      preLoaderRoute: typeof RBarIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/bars/$barId': {
      id: '/app/bars/$barId'
      path: '/bars/$barId'
      fullPath: '/app/bars/$barId'
      preLoaderRoute: typeof AppBarsBarIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/bars/new': {
      id: '/app/bars/new'
      path: '/bars/new'
      fullPath: '/app/bars/new'
      preLoaderRoute: typeof AppBarsNewRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/equipe-bar/': {
      id: '/app/equipe-bar/'
      path: '/equipe-bar'
      fullPath: '/app/equipe-bar/'
      preLoaderRoute: typeof AppEquipeBarIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/equipe-bar/$barId': {
      id: '/app/equipe-bar/$barId'
      path: '/equipe-bar/$barId'
      fullPath: '/app/equipe-bar/$barId'
      preLoaderRoute: typeof AppEquipeBarBarIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/manutencao/': {
      id: '/app/manutencao/'
      path: '/manutencao'
      fullPath: '/app/manutencao/'
      preLoaderRoute: typeof AppManutencaoIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/manutencao/$barId': {
      id: '/app/manutencao/$barId'
      path: '/manutencao/$barId'
      fullPath: '/app/manutencao/$barId'
      preLoaderRoute: typeof AppManutencaoBarIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/r/t/$code': {
      id: '/r/t/$code'
      path: '/r/t/$code'
      fullPath: '/r/t/$code'
      preLoaderRoute: typeof RTCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/backup/daily': {
      id: '/api/public/backup/daily'
      path: '/api/public/backup/daily'
      fullPath: '/api/public/backup/daily'
      preLoaderRoute: typeof ApiPublicBackupDailyRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AppRouteChildren {
  AppBackupsRoute: typeof AppBackupsRoute
  AppBiRoute: typeof AppBiRoute
  AppCargasRoute: typeof AppCargasRoute
  AppCentralRoute: typeof AppCentralRoute
  AppConsumoRoute: typeof AppConsumoRoute
  AppConsumoTempoRoute: typeof AppConsumoTempoRoute
  AppEstoqueRoute: typeof AppEstoqueRoute
  AppGovernancaRoute: typeof AppGovernancaRoute
  AppImportarRoute: typeof AppImportarRoute
  AppInventariosRoute: typeof AppInventariosRoute
  AppMapRoute: typeof AppMapRoute
  AppNotasRoute: typeof AppNotasRoute
  AppPerfilRoute: typeof AppPerfilRoute
  AppRelatorioRoute: typeof AppRelatorioRoute
  AppIndexRoute: typeof AppIndexRoute
  AppBarsBarIdRoute: typeof AppBarsBarIdRoute
  AppBarsNewRoute: typeof AppBarsNewRoute
  AppEquipeBarBarIdRoute: typeof AppEquipeBarBarIdRoute
  AppManutencaoBarIdRoute: typeof AppManutencaoBarIdRoute
  AppEquipeBarIndexRoute: typeof AppEquipeBarIndexRoute
  AppManutencaoIndexRoute: typeof AppManutencaoIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppBackupsRoute: AppBackupsRoute,
  AppBiRoute: AppBiRoute,
  AppCargasRoute: AppCargasRoute,
  AppCentralRoute: AppCentralRoute,
  AppConsumoRoute: AppConsumoRoute,
  AppConsumoTempoRoute: AppConsumoTempoRoute,
  AppEstoqueRoute: AppEstoqueRoute,
  AppGovernancaRoute: AppGovernancaRoute,
  AppImportarRoute: AppImportarRoute,
  AppInventariosRoute: AppInventariosRoute,
  AppMapRoute: AppMapRoute,
  AppNotasRoute: AppNotasRoute,
  AppPerfilRoute: AppPerfilRoute,
  AppRelatorioRoute: AppRelatorioRoute,
  AppIndexRoute: AppIndexRoute,
  AppBarsBarIdRoute: AppBarsBarIdRoute,
  AppBarsNewRoute: AppBarsNewRoute,
  AppEquipeBarBarIdRoute: AppEquipeBarBarIdRoute,
  AppManutencaoBarIdRoute: AppManutencaoBarIdRoute,
  AppEquipeBarIndexRoute: AppEquipeBarIndexRoute,
  AppManutencaoIndexRoute: AppManutencaoIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  AuthRoute: AuthRoute,
  RBarIdRoute: RBarIdRoute,
  RTCodeRoute: RTCodeRoute,
  ApiPublicBackupDailyRoute: ApiPublicBackupDailyRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
