-- =====================================================================
-- DEFINITIVO — CONSUMO consolidado (25/07): baseline único e determinístico.
-- Zera meep_consumo_bar e regrava SOMENTE os 15 bares consolidados
-- (465 H / 467 A). Corrige a duplicação causada por variantes de nome
-- em seeds anteriores (ex.: "Nucleos"/"Núcleos", "Vila"/"Villa",
-- "Choperia"/"Chopperia"). Idempotente: reexecutar dá o mesmo estado.
-- bar_id é resolvido por nome (case/acento-insensível) quando o bar existir.
-- =====================================================================

-- 1) Zera a base de consumo (reconstruída integralmente abaixo).
DELETE FROM public.meep_consumo_bar;

-- 2) Regrava o consolidado (fonte: docs/consumo-25-07-consolidado.csv).
INSERT INTO public.meep_consumo_bar (bar_id, bar_nome, data, marca, barris) VALUES
  ((SELECT id FROM public.bars WHERE translate(lower(btrim(name)),'áàâãäéèêëíìîïóòôõöúùûüç','aaaaaeeeeiiiiooooouuuuc')='chopperia (1+2)' LIMIT 1), 'Chopperia (1+2)', '2026-07-18', 'amstel', 4),
  ((SELECT id FROM public.bars WHERE translate(lower(btrim(name)),'áàâãäéèêëíìîïóòôõöúùûüç','aaaaaeeeeiiiiooooouuuuc')='chopperia (1+2)' LIMIT 1), 'Chopperia (1+2)', '2026-07-18', 'heineken', 5),
  ((SELECT id FROM public.bars WHERE translate(lower(btrim(name)),'áàâãäéèêëíìîïóòôõöúùûüç','aaaaaeeeeiiiiooooouuuuc')='chopperia (1+2)' LIMIT 1), 'Chopperia (1+2)', '2026-07-19', 'amstel', 5),
  ((SELECT id FROM public.bars WHERE translate(lower(btrim(name)),'áàâãäéèêëíìîïóòôõöúùûüç','aaaaaeeeeiiiiooooouuuuc')='chopperia (1+2)' LIMIT 1), 'Chopperia (1+2)', '2026-07-19', 'heineken', 5),
  ((SELECT id FROM public.bars WHERE translate(lower(btrim(name)),'áàâãäéèêëíìîïóòôõöúùûüç','aaaaaeeeeiiiiooooouuuuc')='chopperia (1+2)' LIMIT 1), 'Chopperia (1+2)', '2026-07-20', 'amstel', 1),
  ((SELECT id FROM public.bars WHERE translate(lower(btrim(name)),'áàâãäéèêëíìîïóòôõöúùûüç','aaaaaeeeeiiiiooooouuuuc')='chopperia (1+2)' LIMIT 1), 'Chopperia (1+2)', '2026-07-20', 'heineken', 1),
  ((SELECT id FROM public.bars WHERE translate(lower(btrim(name)),'áàâãäéèêëíìîïóòôõöúùûüç','aaaaaeeeeiiiiooooouuuuc')='chopperia (1+2)' LIMIT 1), 'Chopperia (1+2)', '2026-07-21', 'amstel', 3),
  ((SELECT id FROM public.bars WHERE translate(lower(btrim(name)),'áàâãäéèêëíìîïóòôõöúùûüç','aaaaaeeeeiiiiooooouuuuc')='chopperia (1+2)' LIMIT 1), 'Chopperia (1+2)', '2026-07-21', 'heineken', 2),
  ((SELECT id FROM public.bars WHERE translate(lower(btrim(name)),'áàâãäéèêëíìîïóòôõöúùûüç','aaaaaeeeeiiiiooooouuuuc')='chopperia (1+2)' LIMIT 1), 'Chopperia (1+2)', '2026-07-22', 'amstel', 6),
  ((SELECT id FROM public.bars WHERE translate(lower(btrim(name)),'áàâãäéèêëíìîïóòôõöúùûüç','aaaaaeeeeiiiiooooouuuuc')='chopperia (1+2)' LIMIT 1), 'Chopperia (1+2)', '2026-07-22', 'heineken', 6),
  ((SELECT id FROM public.bars WHERE translate(lower(btrim(name)),'áàâãäéèêëíìîïóòôõöúùûüç','aaaaaeeeeiiiiooooouuuuc')='chopperia (1+2)' LIMIT 1), 'Chopperia (1+2)', '2026-07-23', 'amstel', 17),
  ((SELECT id FROM public.bars WHERE translate(lower(btrim(name)),'áàâãäéèêëíìîïóòôõöúùûüç','aaaaaeeeeiiiiooooouuuuc')='chopperia (1+2)' LIMIT 1), 'Chopperia (1+2)', '2026-07-23', 'heineken', 17),
  ((SELECT id FROM public.bars WHERE translate(lower(btrim(name)),'áàâãäéèêëíìîïóòôõöúùûüç','aaaaaeeeeiiiiooooouuuuc')='chopperia (1+2)' LIMIT 1), 'Chopperia (1+2)', '2026-07-24', 'amstel', 8),
  ((SELECT id FROM public.bars WHERE translate(lower(btrim(name)),'áàâãäéèêëíìîïóòôõöúùûüç','aaaaaeeeeiiiiooooouuuuc')='chopperia (1+2)' LIMIT 1), 'Chopperia (1+2)', '2026-07-24', 'heineken', 7),
  ((SELECT id FROM public.bars WHERE translate(lower(btrim(name)),'áàâãäéèêëíìîïóòôõöúùûüç','aaaaaeeeeiiiiooooouuuuc')='entrada arquibancada' LIMIT 1), 'Entrada arquibancada', '2026-07-18', 'amstel', 16),
  ((SELECT id FROM public.bars WHERE translate(lower(btrim(name)),'áàâãäéèêëíìîïóòôõöúùûüç','aaaaaeeeeiiiiooooouuuuc')='entrada arquibancada' LIMIT 1), 'Entrada arquibancada', '2026-07-18', 'heineken', 16),
  ((SELECT id FROM public.bars WHERE translate(lower(btrim(name)),'áàâãäéèêëíìîïóòôõöúùûüç','aaaaaeeeeiiiiooooouuuuc')='entrada arquibancada' LIMIT 1), 'Entrada arquibancada', '2026-07-21', 'heineken', 1),
  ((SELECT id FROM public.bars WHERE translate(lower(btrim(name)),'áàâãäéèêëíìîïóòôõöúùûüç','aaaaaeeeeiiiiooooouuuuc')='entrada arquibancada' LIMIT 1), 'Entrada arquibancada', '2026-07-22', 'amstel', 3),
  ((SELECT id FROM public.bars WHERE translate(lower(btrim(name)),'áàâãäéèêëíìîïóòôõöúùûüç','aaaaaeeeeiiiiooooouuuuc')='entrada arquibancada' LIMIT 1), 'Entrada arquibancada', '2026-07-22', 'heineken', 2),
  ((SELECT id FROM public.bars WHERE translate(lower(btrim(name)),'áàâãäéèêëíìîïóòôõöúùûüç','aaaaaeeeeiiiiooooouuuuc')='entrada arquibancada' LIMIT 1), 'Entrada arquibancada', '2026-07-23', 'amstel', 11),
  ((SELECT id FROM public.bars WHERE translate(lower(btrim(name)),'áàâãäéèêëíìîïóòôõöúùûüç','aaaaaeeeeiiiiooooouuuuc')='entrada arquibancada' LIMIT 1), 'Entrada arquibancada', '2026-07-23', 'heineken', 10),
  ((SELECT id FROM public.bars WHERE translate(lower(btrim(name)),'áàâãäéèêëíìîïóòôõöúùûüç','aaaaaeeeeiiiiooooouuuuc')='entrada arquibancada' LIMIT 1), 'Entrada arquibancada', '2026-07-24', 'amstel', 4),
  ((SELECT id FROM public.bars WHERE translate(lower(btrim(name)),'áàâãäéèêëíìîïóòôõöúùûüç','aaaaaeeeeiiiiooooouuuuc')='entrada arquibancada' LIMIT 1), 'Entrada arquibancada', '2026-07-24', 'heineken', 4),
  ((SELECT id FROM public.bars WHERE translate(lower(btrim(name)),'áàâãäéèêëíìîïóòôõöúùûüç','aaaaaeeeeiiiiooooouuuuc')='fundo arquibancada' LIMIT 1), 'Fundo arquibancada', '2026-07-18', 'amstel', 8),
  ((SELECT id FROM public.bars WHERE translate(lower(btrim(name)),'áàâãäéèêëíìîïóòôõöúùûüç','aaaaaeeeeiiiiooooouuuuc')='fundo arquibancada' LIMIT 1), 'Fundo arquibancada', '2026-07-18', 'heineken', 8),
  ((SELECT id FROM public.bars WHERE translate(lower(btrim(name)),'áàâãäéèêëíìîïóòôõöúùûüç','aaaaaeeeeiiiiooooouuuuc')='fundo arquibancada' LIMIT 1), 'Fundo arquibancada', '2026-07-23', 'amstel', 8),
  ((SELECT id FROM public.bars WHERE translate(lower(btrim(name)),'áàâãäéèêëíìîïóòôõöúùûüç','aaaaaeeeeiiiiooooouuuuc')='fundo arquibancada' LIMIT 1), 'Fundo arquibancada', '2026-07-23', 'heineken', 7),
  ((SELECT id FROM public.bars WHERE translate(lower(btrim(name)),'áàâãäéèêëíìîïóòôõöúùûüç','aaaaaeeeeiiiiooooouuuuc')='fundo arquibancada' LIMIT 1), 'Fundo arquibancada', '2026-07-24', 'amstel', 2),
  ((SELECT id FROM public.bars WHERE translate(lower(btrim(name)),'áàâãäéèêëíìîïóòôõöúùûüç','aaaaaeeeeiiiiooooouuuuc')='fundo arquibancada' LIMIT 1), 'Fundo arquibancada', '2026-07-24', 'heineken', 1),
  ((SELECT id FROM public.bars WHERE translate(lower(btrim(name)),'áàâãäéèêëíìîïóòôõöúùûüç','aaaaaeeeeiiiiooooouuuuc')='hippos bar' LIMIT 1), 'Hippos bar', '2026-07-18', 'heineken', 10),
  ((SELECT id FROM public.bars WHERE translate(lower(btrim(name)),'áàâãäéèêëíìîïóòôõöúùûüç','aaaaaeeeeiiiiooooouuuuc')='hippos bar' LIMIT 1), 'Hippos bar', '2026-07-23', 'heineken', 6),
  ((SELECT id FROM public.bars WHERE translate(lower(btrim(name)),'áàâãäéèêëíìîïóòôõöúùûüç','aaaaaeeeeiiiiooooouuuuc')='hippos bar' LIMIT 1), 'Hippos bar', '2026-07-24', 'heineken', 10),
  ((SELECT id FROM public.bars WHERE translate(lower(btrim(name)),'áàâãäéèêëíìîïóòôõöúùûüç','aaaaaeeeeiiiiooooouuuuc')='liberdade' LIMIT 1), 'Liberdade', '2026-07-19', 'amstel', 6),
  ((SELECT id FROM public.bars WHERE translate(lower(btrim(name)),'áàâãäéèêëíìîïóòôõöúùûüç','aaaaaeeeeiiiiooooouuuuc')='liberdade' LIMIT 1), 'Liberdade', '2026-07-19', 'heineken', 6),
  ((SELECT id FROM public.bars WHERE translate(lower(btrim(name)),'áàâãäéèêëíìîïóòôõöúùûüç','aaaaaeeeeiiiiooooouuuuc')='liberdade' LIMIT 1), 'Liberdade', '2026-07-21', 'amstel', 3),
  ((SELECT id FROM public.bars WHERE translate(lower(btrim(name)),'áàâãäéèêëíìîïóòôõöúùûüç','aaaaaeeeeiiiiooooouuuuc')='liberdade' LIMIT 1), 'Liberdade', '2026-07-21', 'heineken', 3),
  ((SELECT id FROM public.bars WHERE translate(lower(btrim(name)),'áàâãäéèêëíìîïóòôõöúùûüç','aaaaaeeeeiiiiooooouuuuc')='liberdade' LIMIT 1), 'Liberdade', '2026-07-22', 'amstel', 4),
  ((SELECT id FROM public.bars WHERE translate(lower(btrim(name)),'áàâãäéèêëíìîïóòôõöúùûüç','aaaaaeeeeiiiiooooouuuuc')='liberdade' LIMIT 1), 'Liberdade', '2026-07-22', 'heineken', 4),
  ((SELECT id FROM public.bars WHERE translate(lower(btrim(name)),'áàâãäéèêëíìîïóòôõöúùûüç','aaaaaeeeeiiiiooooouuuuc')='liberdade' LIMIT 1), 'Liberdade', '2026-07-24', 'amstel', 10),
  ((SELECT id FROM public.bars WHERE translate(lower(btrim(name)),'áàâãäéèêëíìîïóòôõöúùûüç','aaaaaeeeeiiiiooooouuuuc')='liberdade' LIMIT 1), 'Liberdade', '2026-07-24', 'heineken', 10),
  ((SELECT id FROM public.bars WHERE translate(lower(btrim(name)),'áàâãäéèêëíìîïóòôõöúùûüç','aaaaaeeeeiiiiooooouuuuc')='meio arquibancada' LIMIT 1), 'Meio arquibancada', '2026-07-18', 'amstel', 8),
  ((SELECT id FROM public.bars WHERE translate(lower(btrim(name)),'áàâãäéèêëíìîïóòôõöúùûüç','aaaaaeeeeiiiiooooouuuuc')='meio arquibancada' LIMIT 1), 'Meio arquibancada', '2026-07-18', 'heineken', 8),
  ((SELECT id FROM public.bars WHERE translate(lower(btrim(name)),'áàâãäéèêëíìîïóòôõöúùûüç','aaaaaeeeeiiiiooooouuuuc')='meio arquibancada' LIMIT 1), 'Meio arquibancada', '2026-07-23', 'amstel', 8),
  ((SELECT id FROM public.bars WHERE translate(lower(btrim(name)),'áàâãäéèêëíìîïóòôõöúùûüç','aaaaaeeeeiiiiooooouuuuc')='meio arquibancada' LIMIT 1), 'Meio arquibancada', '2026-07-23', 'heineken', 8),
  ((SELECT id FROM public.bars WHERE translate(lower(btrim(name)),'áàâãäéèêëíìîïóòôõöúùûüç','aaaaaeeeeiiiiooooouuuuc')='meio arquibancada' LIMIT 1), 'Meio arquibancada', '2026-07-24', 'amstel', 3),
  ((SELECT id FROM public.bars WHERE translate(lower(btrim(name)),'áàâãäéèêëíìîïóòôõöúùûüç','aaaaaeeeeiiiiooooouuuuc')='meio arquibancada' LIMIT 1), 'Meio arquibancada', '2026-07-24', 'heineken', 2),
  ((SELECT id FROM public.bars WHERE translate(lower(btrim(name)),'áàâãäéèêëíìîïóòôõöúùûüç','aaaaaeeeeiiiiooooouuuuc')='nova arquibancada' LIMIT 1), 'Nova arquibancada', '2026-07-18', 'amstel', 8),
  ((SELECT id FROM public.bars WHERE translate(lower(btrim(name)),'áàâãäéèêëíìîïóòôõöúùûüç','aaaaaeeeeiiiiooooouuuuc')='nova arquibancada' LIMIT 1), 'Nova arquibancada', '2026-07-18', 'heineken', 8),
  ((SELECT id FROM public.bars WHERE translate(lower(btrim(name)),'áàâãäéèêëíìîïóòôõöúùûüç','aaaaaeeeeiiiiooooouuuuc')='nova arquibancada' LIMIT 1), 'Nova arquibancada', '2026-07-19', 'amstel', -3),
  ((SELECT id FROM public.bars WHERE translate(lower(btrim(name)),'áàâãäéèêëíìîïóòôõöúùûüç','aaaaaeeeeiiiiooooouuuuc')='nova arquibancada' LIMIT 1), 'Nova arquibancada', '2026-07-19', 'heineken', -3),
  ((SELECT id FROM public.bars WHERE translate(lower(btrim(name)),'áàâãäéèêëíìîïóòôõöúùûüç','aaaaaeeeeiiiiooooouuuuc')='nova arquibancada' LIMIT 1), 'Nova arquibancada', '2026-07-22', 'amstel', 2),
  ((SELECT id FROM public.bars WHERE translate(lower(btrim(name)),'áàâãäéèêëíìîïóòôõöúùûüç','aaaaaeeeeiiiiooooouuuuc')='nova arquibancada' LIMIT 1), 'Nova arquibancada', '2026-07-22', 'heineken', 2),
  ((SELECT id FROM public.bars WHERE translate(lower(btrim(name)),'áàâãäéèêëíìîïóòôõöúùûüç','aaaaaeeeeiiiiooooouuuuc')='nova arquibancada' LIMIT 1), 'Nova arquibancada', '2026-07-23', 'amstel', 12),
  ((SELECT id FROM public.bars WHERE translate(lower(btrim(name)),'áàâãäéèêëíìîïóòôõöúùûüç','aaaaaeeeeiiiiooooouuuuc')='nova arquibancada' LIMIT 1), 'Nova arquibancada', '2026-07-23', 'heineken', 10),
  ((SELECT id FROM public.bars WHERE translate(lower(btrim(name)),'áàâãäéèêëíìîïóòôõöúùûüç','aaaaaeeeeiiiiooooouuuuc')='nova arquibancada' LIMIT 1), 'Nova arquibancada', '2026-07-24', 'amstel', 1),
  ((SELECT id FROM public.bars WHERE translate(lower(btrim(name)),'áàâãäéèêëíìîïóòôõöúùûüç','aaaaaeeeeiiiiooooouuuuc')='nova arquibancada' LIMIT 1), 'Nova arquibancada', '2026-07-24', 'heineken', 1),
  ((SELECT id FROM public.bars WHERE translate(lower(btrim(name)),'áàâãäéèêëíìîïóòôõöúùûüç','aaaaaeeeeiiiiooooouuuuc')='nucleos' LIMIT 1), 'Nucleos', '2026-07-18', 'amstel', 16),
  ((SELECT id FROM public.bars WHERE translate(lower(btrim(name)),'áàâãäéèêëíìîïóòôõöúùûüç','aaaaaeeeeiiiiooooouuuuc')='nucleos' LIMIT 1), 'Nucleos', '2026-07-18', 'heineken', 16),
  ((SELECT id FROM public.bars WHERE translate(lower(btrim(name)),'áàâãäéèêëíìîïóòôõöúùûüç','aaaaaeeeeiiiiooooouuuuc')='nucleos' LIMIT 1), 'Nucleos', '2026-07-22', 'amstel', 3),
  ((SELECT id FROM public.bars WHERE translate(lower(btrim(name)),'áàâãäéèêëíìîïóòôõöúùûüç','aaaaaeeeeiiiiooooouuuuc')='nucleos' LIMIT 1), 'Nucleos', '2026-07-22', 'heineken', 1),
  ((SELECT id FROM public.bars WHERE translate(lower(btrim(name)),'áàâãäéèêëíìîïóòôõöúùûüç','aaaaaeeeeiiiiooooouuuuc')='nucleos' LIMIT 1), 'Nucleos', '2026-07-23', 'amstel', 21),
  ((SELECT id FROM public.bars WHERE translate(lower(btrim(name)),'áàâãäéèêëíìîïóòôõöúùûüç','aaaaaeeeeiiiiooooouuuuc')='nucleos' LIMIT 1), 'Nucleos', '2026-07-23', 'heineken', 19),
  ((SELECT id FROM public.bars WHERE translate(lower(btrim(name)),'áàâãäéèêëíìîïóòôõöúùûüç','aaaaaeeeeiiiiooooouuuuc')='pista de areia' LIMIT 1), 'Pista de areia', '2026-07-21', 'amstel', 1),
  ((SELECT id FROM public.bars WHERE translate(lower(btrim(name)),'áàâãäéèêëíìîïóòôõöúùûüç','aaaaaeeeeiiiiooooouuuuc')='pista de areia' LIMIT 1), 'Pista de areia', '2026-07-21', 'heineken', 1),
  ((SELECT id FROM public.bars WHERE translate(lower(btrim(name)),'áàâãäéèêëíìîïóòôõöúùûüç','aaaaaeeeeiiiiooooouuuuc')='vila 3 maior' LIMIT 1), 'Vila 3 maior', '2026-07-18', 'amstel', 10),
  ((SELECT id FROM public.bars WHERE translate(lower(btrim(name)),'áàâãäéèêëíìîïóòôõöúùûüç','aaaaaeeeeiiiiooooouuuuc')='vila 3 maior' LIMIT 1), 'Vila 3 maior', '2026-07-18', 'heineken', 10),
  ((SELECT id FROM public.bars WHERE translate(lower(btrim(name)),'áàâãäéèêëíìîïóòôõöúùûüç','aaaaaeeeeiiiiooooouuuuc')='vila 3 maior' LIMIT 1), 'Vila 3 maior', '2026-07-22', 'amstel', 3),
  ((SELECT id FROM public.bars WHERE translate(lower(btrim(name)),'áàâãäéèêëíìîïóòôõöúùûüç','aaaaaeeeeiiiiooooouuuuc')='vila 3 maior' LIMIT 1), 'Vila 3 maior', '2026-07-22', 'heineken', 4),
  ((SELECT id FROM public.bars WHERE translate(lower(btrim(name)),'áàâãäéèêëíìîïóòôõöúùûüç','aaaaaeeeeiiiiooooouuuuc')='vila 3 maior' LIMIT 1), 'Vila 3 maior', '2026-07-23', 'amstel', 21),
  ((SELECT id FROM public.bars WHERE translate(lower(btrim(name)),'áàâãäéèêëíìîïóòôõöúùûüç','aaaaaeeeeiiiiooooouuuuc')='vila 3 maior' LIMIT 1), 'Vila 3 maior', '2026-07-23', 'heineken', 19),
  ((SELECT id FROM public.bars WHERE translate(lower(btrim(name)),'áàâãäéèêëíìîïóòôõöúùûüç','aaaaaeeeeiiiiooooouuuuc')='vila 3 maior' LIMIT 1), 'Vila 3 maior', '2026-07-24', 'amstel', 6),
  ((SELECT id FROM public.bars WHERE translate(lower(btrim(name)),'áàâãäéèêëíìîïóòôõöúùûüç','aaaaaeeeeiiiiooooouuuuc')='vila 3 maior' LIMIT 1), 'Vila 3 maior', '2026-07-24', 'heineken', 5),
  ((SELECT id FROM public.bars WHERE translate(lower(btrim(name)),'áàâãäéèêëíìîïóòôõöúùûüç','aaaaaeeeeiiiiooooouuuuc')='villa 1 autoatendimento' LIMIT 1), 'Villa 1 autoatendimento', '2026-07-18', 'amstel', 16),
  ((SELECT id FROM public.bars WHERE translate(lower(btrim(name)),'áàâãäéèêëíìîïóòôõöúùûüç','aaaaaeeeeiiiiooooouuuuc')='villa 1 autoatendimento' LIMIT 1), 'Villa 1 autoatendimento', '2026-07-18', 'heineken', 16),
  ((SELECT id FROM public.bars WHERE translate(lower(btrim(name)),'áàâãäéèêëíìîïóòôõöúùûüç','aaaaaeeeeiiiiooooouuuuc')='villa 1 autoatendimento' LIMIT 1), 'Villa 1 autoatendimento', '2026-07-19', 'amstel', 3),
  ((SELECT id FROM public.bars WHERE translate(lower(btrim(name)),'áàâãäéèêëíìîïóòôõöúùûüç','aaaaaeeeeiiiiooooouuuuc')='villa 1 autoatendimento' LIMIT 1), 'Villa 1 autoatendimento', '2026-07-19', 'heineken', 3),
  ((SELECT id FROM public.bars WHERE translate(lower(btrim(name)),'áàâãäéèêëíìîïóòôõöúùûüç','aaaaaeeeeiiiiooooouuuuc')='villa 1 autoatendimento' LIMIT 1), 'Villa 1 autoatendimento', '2026-07-21', 'amstel', 4),
  ((SELECT id FROM public.bars WHERE translate(lower(btrim(name)),'áàâãäéèêëíìîïóòôõöúùûüç','aaaaaeeeeiiiiooooouuuuc')='villa 1 autoatendimento' LIMIT 1), 'Villa 1 autoatendimento', '2026-07-22', 'amstel', 4),
  ((SELECT id FROM public.bars WHERE translate(lower(btrim(name)),'áàâãäéèêëíìîïóòôõöúùûüç','aaaaaeeeeiiiiooooouuuuc')='villa 1 autoatendimento' LIMIT 1), 'Villa 1 autoatendimento', '2026-07-22', 'heineken', 9),
  ((SELECT id FROM public.bars WHERE translate(lower(btrim(name)),'áàâãäéèêëíìîïóòôõöúùûüç','aaaaaeeeeiiiiooooouuuuc')='villa 1 autoatendimento' LIMIT 1), 'Villa 1 autoatendimento', '2026-07-23', 'amstel', 28),
  ((SELECT id FROM public.bars WHERE translate(lower(btrim(name)),'áàâãäéèêëíìîïóòôõöúùûüç','aaaaaeeeeiiiiooooouuuuc')='villa 1 autoatendimento' LIMIT 1), 'Villa 1 autoatendimento', '2026-07-23', 'heineken', 21),
  ((SELECT id FROM public.bars WHERE translate(lower(btrim(name)),'áàâãäéèêëíìîïóòôõöúùûüç','aaaaaeeeeiiiiooooouuuuc')='villa 1 autoatendimento' LIMIT 1), 'Villa 1 autoatendimento', '2026-07-24', 'amstel', 13),
  ((SELECT id FROM public.bars WHERE translate(lower(btrim(name)),'áàâãäéèêëíìîïóòôõöúùûüç','aaaaaeeeeiiiiooooouuuuc')='villa 1 autoatendimento' LIMIT 1), 'Villa 1 autoatendimento', '2026-07-24', 'heineken', 11),
  ((SELECT id FROM public.bars WHERE translate(lower(btrim(name)),'áàâãäéèêëíìîïóòôõöúùûüç','aaaaaeeeeiiiiooooouuuuc')='villa 2 autoatendimento' LIMIT 1), 'Villa 2 autoatendimento', '2026-07-18', 'amstel', 14),
  ((SELECT id FROM public.bars WHERE translate(lower(btrim(name)),'áàâãäéèêëíìîïóòôõöúùûüç','aaaaaeeeeiiiiooooouuuuc')='villa 2 autoatendimento' LIMIT 1), 'Villa 2 autoatendimento', '2026-07-18', 'heineken', 14),
  ((SELECT id FROM public.bars WHERE translate(lower(btrim(name)),'áàâãäéèêëíìîïóòôõöúùûüç','aaaaaeeeeiiiiooooouuuuc')='villa 2 autoatendimento' LIMIT 1), 'Villa 2 autoatendimento', '2026-07-19', 'amstel', 5),
  ((SELECT id FROM public.bars WHERE translate(lower(btrim(name)),'áàâãäéèêëíìîïóòôõöúùûüç','aaaaaeeeeiiiiooooouuuuc')='villa 2 autoatendimento' LIMIT 1), 'Villa 2 autoatendimento', '2026-07-19', 'heineken', 4),
  ((SELECT id FROM public.bars WHERE translate(lower(btrim(name)),'áàâãäéèêëíìîïóòôõöúùûüç','aaaaaeeeeiiiiooooouuuuc')='villa 2 autoatendimento' LIMIT 1), 'Villa 2 autoatendimento', '2026-07-20', 'amstel', 4),
  ((SELECT id FROM public.bars WHERE translate(lower(btrim(name)),'áàâãäéèêëíìîïóòôõöúùûüç','aaaaaeeeeiiiiooooouuuuc')='villa 2 autoatendimento' LIMIT 1), 'Villa 2 autoatendimento', '2026-07-20', 'heineken', 4),
  ((SELECT id FROM public.bars WHERE translate(lower(btrim(name)),'áàâãäéèêëíìîïóòôõöúùûüç','aaaaaeeeeiiiiooooouuuuc')='villa 2 autoatendimento' LIMIT 1), 'Villa 2 autoatendimento', '2026-07-22', 'amstel', 7),
  ((SELECT id FROM public.bars WHERE translate(lower(btrim(name)),'áàâãäéèêëíìîïóòôõöúùûüç','aaaaaeeeeiiiiooooouuuuc')='villa 2 autoatendimento' LIMIT 1), 'Villa 2 autoatendimento', '2026-07-22', 'heineken', 5),
  ((SELECT id FROM public.bars WHERE translate(lower(btrim(name)),'áàâãäéèêëíìîïóòôõöúùûüç','aaaaaeeeeiiiiooooouuuuc')='villa 2 autoatendimento' LIMIT 1), 'Villa 2 autoatendimento', '2026-07-23', 'amstel', 20),
  ((SELECT id FROM public.bars WHERE translate(lower(btrim(name)),'áàâãäéèêëíìîïóòôõöúùûüç','aaaaaeeeeiiiiooooouuuuc')='villa 2 autoatendimento' LIMIT 1), 'Villa 2 autoatendimento', '2026-07-23', 'heineken', 19),
  ((SELECT id FROM public.bars WHERE translate(lower(btrim(name)),'áàâãäéèêëíìîïóòôõöúùûüç','aaaaaeeeeiiiiooooouuuuc')='villa 2 autoatendimento' LIMIT 1), 'Villa 2 autoatendimento', '2026-07-24', 'amstel', 16),
  ((SELECT id FROM public.bars WHERE translate(lower(btrim(name)),'áàâãäéèêëíìîïóòôõöúùûüç','aaaaaeeeeiiiiooooouuuuc')='villa 2 autoatendimento' LIMIT 1), 'Villa 2 autoatendimento', '2026-07-24', 'heineken', 16),
  ((SELECT id FROM public.bars WHERE translate(lower(btrim(name)),'áàâãäéèêëíìîïóòôõöúùûüç','aaaaaeeeeiiiiooooouuuuc')='villa 2 menor' LIMIT 1), 'Villa 2 menor', '2026-07-18', 'amstel', 6),
  ((SELECT id FROM public.bars WHERE translate(lower(btrim(name)),'áàâãäéèêëíìîïóòôõöúùûüç','aaaaaeeeeiiiiooooouuuuc')='villa 2 menor' LIMIT 1), 'Villa 2 menor', '2026-07-18', 'heineken', 6),
  ((SELECT id FROM public.bars WHERE translate(lower(btrim(name)),'áàâãäéèêëíìîïóòôõöúùûüç','aaaaaeeeeiiiiooooouuuuc')='villa 2 menor' LIMIT 1), 'Villa 2 menor', '2026-07-21', 'amstel', 2),
  ((SELECT id FROM public.bars WHERE translate(lower(btrim(name)),'áàâãäéèêëíìîïóòôõöúùûüç','aaaaaeeeeiiiiooooouuuuc')='villa 2 menor' LIMIT 1), 'Villa 2 menor', '2026-07-21', 'heineken', 2),
  ((SELECT id FROM public.bars WHERE translate(lower(btrim(name)),'áàâãäéèêëíìîïóòôõöúùûüç','aaaaaeeeeiiiiooooouuuuc')='villa 2 menor' LIMIT 1), 'Villa 2 menor', '2026-07-22', 'amstel', 3),
  ((SELECT id FROM public.bars WHERE translate(lower(btrim(name)),'áàâãäéèêëíìîïóòôõöúùûüç','aaaaaeeeeiiiiooooouuuuc')='villa 2 menor' LIMIT 1), 'Villa 2 menor', '2026-07-22', 'heineken', 1),
  ((SELECT id FROM public.bars WHERE translate(lower(btrim(name)),'áàâãäéèêëíìîïóòôõöúùûüç','aaaaaeeeeiiiiooooouuuuc')='villa 2 menor' LIMIT 1), 'Villa 2 menor', '2026-07-23', 'amstel', 12),
  ((SELECT id FROM public.bars WHERE translate(lower(btrim(name)),'áàâãäéèêëíìîïóòôõöúùûüç','aaaaaeeeeiiiiooooouuuuc')='villa 2 menor' LIMIT 1), 'Villa 2 menor', '2026-07-23', 'heineken', 11),
  ((SELECT id FROM public.bars WHERE translate(lower(btrim(name)),'áàâãäéèêëíìîïóòôõöúùûüç','aaaaaeeeeiiiiooooouuuuc')='villa 2 menor' LIMIT 1), 'Villa 2 menor', '2026-07-24', 'amstel', 2),
  ((SELECT id FROM public.bars WHERE translate(lower(btrim(name)),'áàâãäéèêëíìîïóòôõöúùûüç','aaaaaeeeeiiiiooooouuuuc')='villa 2 menor' LIMIT 1), 'Villa 2 menor', '2026-07-24', 'heineken', 3),
  ((SELECT id FROM public.bars WHERE translate(lower(btrim(name)),'áàâãäéèêëíìîïóòôõöúùûüç','aaaaaeeeeiiiiooooouuuuc')='villa 3 menor' LIMIT 1), 'Villa 3 menor', '2026-07-18', 'amstel', 6),
  ((SELECT id FROM public.bars WHERE translate(lower(btrim(name)),'áàâãäéèêëíìîïóòôõöúùûüç','aaaaaeeeeiiiiooooouuuuc')='villa 3 menor' LIMIT 1), 'Villa 3 menor', '2026-07-18', 'heineken', 6),
  ((SELECT id FROM public.bars WHERE translate(lower(btrim(name)),'áàâãäéèêëíìîïóòôõöúùûüç','aaaaaeeeeiiiiooooouuuuc')='villa 3 menor' LIMIT 1), 'Villa 3 menor', '2026-07-23', 'amstel', 13),
  ((SELECT id FROM public.bars WHERE translate(lower(btrim(name)),'áàâãäéèêëíìîïóòôõöúùûüç','aaaaaeeeeiiiiooooouuuuc')='villa 3 menor' LIMIT 1), 'Villa 3 menor', '2026-07-23', 'heineken', 12),
  ((SELECT id FROM public.bars WHERE translate(lower(btrim(name)),'áàâãäéèêëíìîïóòôõöúùûüç','aaaaaeeeeiiiiooooouuuuc')='zel cafe' LIMIT 1), 'Zel café', '2026-07-18', 'amstel', 10),
  ((SELECT id FROM public.bars WHERE translate(lower(btrim(name)),'áàâãäéèêëíìîïóòôõöúùûüç','aaaaaeeeeiiiiooooouuuuc')='zel cafe' LIMIT 1), 'Zel café', '2026-07-18', 'heineken', 10),
  ((SELECT id FROM public.bars WHERE translate(lower(btrim(name)),'áàâãäéèêëíìîïóòôõöúùûüç','aaaaaeeeeiiiiooooouuuuc')='zel cafe' LIMIT 1), 'Zel café', '2026-07-19', 'amstel', 10),
  ((SELECT id FROM public.bars WHERE translate(lower(btrim(name)),'áàâãäéèêëíìîïóòôõöúùûüç','aaaaaeeeeiiiiooooouuuuc')='zel cafe' LIMIT 1), 'Zel café', '2026-07-19', 'heineken', 10),
  ((SELECT id FROM public.bars WHERE translate(lower(btrim(name)),'áàâãäéèêëíìîïóòôõöúùûüç','aaaaaeeeeiiiiooooouuuuc')='zel cafe' LIMIT 1), 'Zel café', '2026-07-22', 'amstel', 10),
  ((SELECT id FROM public.bars WHERE translate(lower(btrim(name)),'áàâãäéèêëíìîïóòôõöúùûüç','aaaaaeeeeiiiiooooouuuuc')='zel cafe' LIMIT 1), 'Zel café', '2026-07-22', 'heineken', 10),
  ((SELECT id FROM public.bars WHERE translate(lower(btrim(name)),'áàâãäéèêëíìîïóòôõöúùûüç','aaaaaeeeeiiiiooooouuuuc')='zel cafe' LIMIT 1), 'Zel café', '2026-07-23', 'amstel', 10),
  ((SELECT id FROM public.bars WHERE translate(lower(btrim(name)),'áàâãäéèêëíìîïóòôõöúùûüç','aaaaaeeeeiiiiooooouuuuc')='zel cafe' LIMIT 1), 'Zel café', '2026-07-23', 'heineken', 10),
  ((SELECT id FROM public.bars WHERE translate(lower(btrim(name)),'áàâãäéèêëíìîïóòôõöúùûüç','aaaaaeeeeiiiiooooouuuuc')='zel cafe' LIMIT 1), 'Zel café', '2026-07-24', 'amstel', 10),
  ((SELECT id FROM public.bars WHERE translate(lower(btrim(name)),'áàâãäéèêëíìîïóòôõöúùûüç','aaaaaeeeeiiiiooooouuuuc')='zel cafe' LIMIT 1), 'Zel café', '2026-07-24', 'heineken', 10)
ON CONFLICT (bar_nome,data,marca) DO UPDATE SET barris = EXCLUDED.barris, bar_id = EXCLUDED.bar_id;
